include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    always_put_required_named_parameters_first: false
    one_member_abstracts: false
    no_default_cases: false
    require_trailing_commas: false
    library_prefixes: false
    flutter_style_todos: false
